/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VetementsRouteImport } from './routes/vetements'
import { Route as StoreRouteImport } from './routes/store'
import { Route as PrestigeHommeRouteImport } from './routes/prestige-homme'
import { Route as PrestigeFemmeRouteImport } from './routes/prestige-femme'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HommeRouteImport } from './routes/homme'
import { Route as FemmeRouteImport } from './routes/femme'
import { Route as DiffuseurRouteImport } from './routes/diffuseur'
import { Route as CosmetiquesRouteImport } from './routes/cosmetiques'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AproposRouteImport } from './routes/apropos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessoiresRouteImport } from './routes/accessoires'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VetementsRoute = VetementsRouteImport.update({
  id: '/vetements',
  path: '/vetements',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestigeHommeRoute = PrestigeHommeRouteImport.update({
  id: '/prestige-homme',
  path: '/prestige-homme',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestigeFemmeRoute = PrestigeFemmeRouteImport.update({
  id: '/prestige-femme',
  path: '/prestige-femme',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HommeRoute = HommeRouteImport.update({
  id: '/homme',
  path: '/homme',
  getParentRoute: () => rootRouteImport,
} as any)
const FemmeRoute = FemmeRouteImport.update({
  id: '/femme',
  path: '/femme',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffuseurRoute = DiffuseurRouteImport.update({
  id: '/diffuseur',
  path: '/diffuseur',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmetiquesRoute = CosmetiquesRouteImport.update({
  id: '/cosmetiques',
  path: '/cosmetiques',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AproposRoute = AproposRouteImport.update({
  id: '/apropos',
  path: '/apropos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoiresRoute = AccessoiresRouteImport.update({
  id: '/accessoires',
  path: '/accessoires',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/admin': typeof AdminRoute
  '/apropos': typeof AproposRoute
  '/contact': typeof ContactRoute
  '/cosmetiques': typeof CosmetiquesRoute
  '/diffuseur': typeof DiffuseurRoute
  '/femme': typeof FemmeRoute
  '/homme': typeof HommeRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/panier': typeof PanierRoute
  '/prestige-femme': typeof PrestigeFemmeRoute
  '/prestige-homme': typeof PrestigeHommeRoute
  '/store': typeof StoreRoute
  '/vetements': typeof VetementsRoute
  '/wishlist': typeof WishlistRoute
  '/listing/$id': typeof ListingIdRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/admin': typeof AdminRoute
  '/apropos': typeof AproposRoute
  '/contact': typeof ContactRoute
  '/cosmetiques': typeof CosmetiquesRoute
  '/diffuseur': typeof DiffuseurRoute
  '/femme': typeof FemmeRoute
  '/homme': typeof HommeRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/panier': typeof PanierRoute
  '/prestige-femme': typeof PrestigeFemmeRoute
  '/prestige-homme': typeof PrestigeHommeRoute
  '/store': typeof StoreRoute
  '/vetements': typeof VetementsRoute
  '/wishlist': typeof WishlistRoute
  '/listing/$id': typeof ListingIdRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/admin': typeof AdminRoute
  '/apropos': typeof AproposRoute
  '/contact': typeof ContactRoute
  '/cosmetiques': typeof CosmetiquesRoute
  '/diffuseur': typeof DiffuseurRoute
  '/femme': typeof FemmeRoute
  '/homme': typeof HommeRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/panier': typeof PanierRoute
  '/prestige-femme': typeof PrestigeFemmeRoute
  '/prestige-homme': typeof PrestigeHommeRoute
  '/store': typeof StoreRoute
  '/vetements': typeof VetementsRoute
  '/wishlist': typeof WishlistRoute
  '/listing/$id': typeof ListingIdRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessoires'
    | '/admin'
    | '/apropos'
    | '/contact'
    | '/cosmetiques'
    | '/diffuseur'
    | '/femme'
    | '/homme'
    | '/login'
    | '/marketplace'
    | '/panier'
    | '/prestige-femme'
    | '/prestige-homme'
    | '/store'
    | '/vetements'
    | '/wishlist'
    | '/listing/$id'
    | '/marketplace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessoires'
    | '/admin'
    | '/apropos'
    | '/contact'
    | '/cosmetiques'
    | '/diffuseur'
    | '/femme'
    | '/homme'
    | '/login'
    | '/marketplace'
    | '/panier'
    | '/prestige-femme'
    | '/prestige-homme'
    | '/store'
    | '/vetements'
    | '/wishlist'
    | '/listing/$id'
    | '/marketplace/$id'
  id:
    | '__root__'
    | '/'
    | '/accessoires'
    | '/admin'
    | '/apropos'
    | '/contact'
    | '/cosmetiques'
    | '/diffuseur'
    | '/femme'
    | '/homme'
    | '/login'
    | '/marketplace'
    | '/panier'
    | '/prestige-femme'
    | '/prestige-homme'
    | '/store'
    | '/vetements'
    | '/wishlist'
    | '/listing/$id'
    | '/marketplace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoiresRoute: typeof AccessoiresRoute
  AdminRoute: typeof AdminRoute
  AproposRoute: typeof AproposRoute
  ContactRoute: typeof ContactRoute
  CosmetiquesRoute: typeof CosmetiquesRoute
  DiffuseurRoute: typeof DiffuseurRoute
  FemmeRoute: typeof FemmeRoute
  HommeRoute: typeof HommeRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  PanierRoute: typeof PanierRoute
  PrestigeFemmeRoute: typeof PrestigeFemmeRoute
  PrestigeHommeRoute: typeof PrestigeHommeRoute
  StoreRoute: typeof StoreRoute
  VetementsRoute: typeof VetementsRoute
  WishlistRoute: typeof WishlistRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vetements': {
      id: '/vetements'
      path: '/vetements'
      fullPath: '/vetements'
      preLoaderRoute: typeof VetementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestige-homme': {
      id: '/prestige-homme'
      path: '/prestige-homme'
      fullPath: '/prestige-homme'
      preLoaderRoute: typeof PrestigeHommeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestige-femme': {
      id: '/prestige-femme'
      path: '/prestige-femme'
      fullPath: '/prestige-femme'
      preLoaderRoute: typeof PrestigeFemmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homme': {
      id: '/homme'
      path: '/homme'
      fullPath: '/homme'
      preLoaderRoute: typeof HommeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/femme': {
      id: '/femme'
      path: '/femme'
      fullPath: '/femme'
      preLoaderRoute: typeof FemmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diffuseur': {
      id: '/diffuseur'
      path: '/diffuseur'
      fullPath: '/diffuseur'
      preLoaderRoute: typeof DiffuseurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetiques': {
      id: '/cosmetiques'
      path: '/cosmetiques'
      fullPath: '/cosmetiques'
      preLoaderRoute: typeof CosmetiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apropos': {
      id: '/apropos'
      path: '/apropos'
      fullPath: '/apropos'
      preLoaderRoute: typeof AproposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessoires': {
      id: '/accessoires'
      path: '/accessoires'
      fullPath: '/accessoires'
      preLoaderRoute: typeof AccessoiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoiresRoute: AccessoiresRoute,
  AdminRoute: AdminRoute,
  AproposRoute: AproposRoute,
  ContactRoute: ContactRoute,
  CosmetiquesRoute: CosmetiquesRoute,
  DiffuseurRoute: DiffuseurRoute,
  FemmeRoute: FemmeRoute,
  HommeRoute: HommeRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  PanierRoute: PanierRoute,
  PrestigeFemmeRoute: PrestigeFemmeRoute,
  PrestigeHommeRoute: PrestigeHommeRoute,
  StoreRoute: StoreRoute,
  VetementsRoute: VetementsRoute,
  WishlistRoute: WishlistRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
