/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VetementsRouteImport } from './routes/vetements'
import { Route as HommeRouteImport } from './routes/homme'
import { Route as FemmeRouteImport } from './routes/femme'
import { Route as DiffuseurRouteImport } from './routes/diffuseur'
import { Route as CosmetiquesRouteImport } from './routes/cosmetiques'
import { Route as AccessoiresRouteImport } from './routes/accessoires'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const VetementsRoute = VetementsRouteImport.update({
  id: '/vetements',
  path: '/vetements',
  getParentRoute: () => rootRouteImport,
} as any)
const HommeRoute = HommeRouteImport.update({
  id: '/homme',
  path: '/homme',
  getParentRoute: () => rootRouteImport,
} as any)
const FemmeRoute = FemmeRouteImport.update({
  id: '/femme',
  path: '/femme',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffuseurRoute = DiffuseurRouteImport.update({
  id: '/diffuseur',
  path: '/diffuseur',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmetiquesRoute = CosmetiquesRouteImport.update({
  id: '/cosmetiques',
  path: '/cosmetiques',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoiresRoute = AccessoiresRouteImport.update({
  id: '/accessoires',
  path: '/accessoires',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/cosmetiques': typeof CosmetiquesRoute
  '/diffuseur': typeof DiffuseurRoute
  '/femme': typeof FemmeRoute
  '/homme': typeof HommeRoute
  '/vetements': typeof VetementsRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/cosmetiques': typeof CosmetiquesRoute
  '/diffuseur': typeof DiffuseurRoute
  '/femme': typeof FemmeRoute
  '/homme': typeof HommeRoute
  '/vetements': typeof VetementsRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/cosmetiques': typeof CosmetiquesRoute
  '/diffuseur': typeof DiffuseurRoute
  '/femme': typeof FemmeRoute
  '/homme': typeof HommeRoute
  '/vetements': typeof VetementsRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessoires'
    | '/cosmetiques'
    | '/diffuseur'
    | '/femme'
    | '/homme'
    | '/vetements'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessoires'
    | '/cosmetiques'
    | '/diffuseur'
    | '/femme'
    | '/homme'
    | '/vetements'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/accessoires'
    | '/cosmetiques'
    | '/diffuseur'
    | '/femme'
    | '/homme'
    | '/vetements'
    | '/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoiresRoute: typeof AccessoiresRoute
  CosmetiquesRoute: typeof CosmetiquesRoute
  DiffuseurRoute: typeof DiffuseurRoute
  FemmeRoute: typeof FemmeRoute
  HommeRoute: typeof HommeRoute
  VetementsRoute: typeof VetementsRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vetements': {
      id: '/vetements'
      path: '/vetements'
      fullPath: '/vetements'
      preLoaderRoute: typeof VetementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homme': {
      id: '/homme'
      path: '/homme'
      fullPath: '/homme'
      preLoaderRoute: typeof HommeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/femme': {
      id: '/femme'
      path: '/femme'
      fullPath: '/femme'
      preLoaderRoute: typeof FemmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diffuseur': {
      id: '/diffuseur'
      path: '/diffuseur'
      fullPath: '/diffuseur'
      preLoaderRoute: typeof DiffuseurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetiques': {
      id: '/cosmetiques'
      path: '/cosmetiques'
      fullPath: '/cosmetiques'
      preLoaderRoute: typeof CosmetiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessoires': {
      id: '/accessoires'
      path: '/accessoires'
      fullPath: '/accessoires'
      preLoaderRoute: typeof AccessoiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoiresRoute: AccessoiresRoute,
  CosmetiquesRoute: CosmetiquesRoute,
  DiffuseurRoute: DiffuseurRoute,
  FemmeRoute: FemmeRoute,
  HommeRoute: HommeRoute,
  VetementsRoute: VetementsRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
